### ISSUE TITLE
Feature: Add support for Avro output format

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/datagen#3]
The feature should include:

```[tasklist]
### Tasks
- [ ] Create a `avroDataGenerator` method
- [ ] Add a schema registry details
- [ ] Update the documentation to include the extra details
- [ ] Add tests to verify that the avro encoding works
```

**Comment by chuck-alt-delete** [comment]
When produce avro to Kafka, the client would also need schema registry credentials, correct? Should SR support be a separate issue?

**Comment by bobbyiliev** [comment]
> When produce avro to Kafka, the client would also need schema registry credentials, correct? Should SR support be a separate issue?

Good point @chuck-alt-delete! I just updated the details to include a CSR in the feature request!

**Comment by chuck-alt-delete** [comment]
I think I’ll tackle this today. For reference:
- https://www.npmjs.com/package/@kafkajs/confluent-schema-registry
